### ISSUE TITLE
Integrate KOrganizer calendars/events

### ISSUE THREAD

**Issue by muesli** [Zren/plasma-applet-eventcalendar#101]
Was expecting it to show calendars & upcoming events from my collection of KOrganizer calendars. But it looks like only special calendars (Holidays) and Google Calendar is currently supported.

**Comment by Zren** [comment]
It'll show any events the default widget (Digital Clock) can. I think you need KDE PIM or something for Digital Clock to show events from KOrganizer.

**Comment by muesli** [comment]
I do have KDE PIM, of course. So this sounds like something I need to configure externally of the applet? Any idea where that would be?

**Comment by Zren** [comment]
I made a video to demonstrate how to enable the KOrganizer events in Digital Clock. The same process should be the same for Events Calendar.

You probably need the `kdepim-addons` package, which should contain the "calendar events plugin" to show the events in the panel.

https://www.youtube.com/watch?v=sTDdXjHIXBA

**Comment by muesli** [comment]
Thanks, got it working!
