### ISSUE TITLE
Google calendar tab and Qt error

### ISSUE THREAD

**Issue by hosein2398** [Zren/plasma-applet-eventcalendar#102]
Hey,
When I open Google Calendar tab I face this error

![Screenshot_20191023_105359](https://user-images.githubusercontent.com/17067774/67368021-73924f00-f583-11e9-8f97-d71f8f972fcf.jpeg)

What's wrong? I have Qt installed.

**Comment by Zren** [comment]
I accidentally imported a super recent version of QtQuickControls2 when I could have imported a really old version. My bad, please try v65.

**Comment by hosein2398** [comment]
Thank you!
It's fixed.
