### ISSUE TITLE
Google Calendar Not Synced on Login?

### ISSUE THREAD

**Issue by IslandCarl** [Zren/plasma-applet-eventcalendar#113]
I've recently discovered this awesome applet but one slight snag I've been having is that the applet won't sync to Google when I login unless I hit the refresh button? I think it does eventually refresh but it takes around 20 minutes, I suspect it will be because my WiFi takes a few seconds after login to connect and so the applet is trying to refresh before I have internet access? is there a way for the applet to store a cached version of my Google Calendar/Events etc. and then just update after a set period of time? or make the applet auto refresh after a set period of time after login? Apologies if this has been answered before but I couldn't find any info surrounding this issue.

Operating System: Arch Linux 
KDE Plasma Version: 5.17.4
KDE Frameworks Version: 5.65.0
Qt Version: 5.14.0
Kernel Version: 4.19.91-1-lts
OS Type: 64-bit

**Comment by Zren** [comment]
v73 should automatically refresh when it detects an internet connection.
