### ISSUE TITLE
Question about modifying clock settings

### ISSUE THREAD

**Issue by afettouhi** [Zren/plasma-applet-eventcalendar#115]
Is it possible to display the local timezone as well as the time and date under the clock options?

**Comment by Zren** [comment]
The [Time Format Documentation](https://doc.qt.io/qt-5/qml-qtqml-qt.html#formatDateTime-method) linked in the config should mention the `t` variable which will be replaced with `EST` for eastern timezone. Eg: `h:mm t`

**Comment by afettouhi** [comment]
Thanks for the link. I can see that config option but I was actually looking for a way to display not CET but the town, e.g. Copenhagen which is my timezone.

**Comment by Zren** [comment]
Uh no. That would require looking up your location. You could manually wrap `'Copenhagen'` in single quotes to print that text literally, but it wouldn't change.

You'd need geolocation to figure out the city you're in. You'd need a seperate widget to print that text, as I'm not interested in adding that feature and making the clock rendering even more complicated.

* https://github.com/KDE/plasma-workspace/tree/master/dataengines/geolocation
* https://github.com/KDE/plasma-workspace/blob/master/dataengines/geolocation/location_ip.cpp#L59
* https://github.com/KDE/plasma-workspace/blob/master/dataengines/geolocation/location_ip.cpp#L178
* https://location.services.mozilla.com

**Comment by afettouhi** [comment]
OK, thanks for the info.
