### ISSUE TITLE
No sound notification Kubuntu 20.04

### ISSUE THREAD

**Issue by HarDX** [Zren/plasma-applet-eventcalendar#128]
No sound notification
Change sound in applet to:
file:///usr/share/sounds/freedesktop/stereo/complete.oga
But not helped

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.67.0
Qt Version: 5.12.5
Kernel Version: 5.4.0-18-generic
OS Type: 64-bit

**Comment by HarDX** [comment]
Try play
`cd .local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/scripts`
`python3 notification.py --sound /usr/share/sounds/freedesktop/stereo/complete.oga test tets`

No sound too

**Comment by HarDX** [comment]
I found problem:
need install
`sudo apt install gnome-session-canberra`

but maybe better use gsound or sox (play command)?
for gsound
```
import gi
gi.require_version('GSound', '1.0')
from gi.repository import GLib, GSound

test = GSound.Context()
test.init()
test.play_simple({GSound.ATTR_EVENT_ID: "complete",
                   GSound.ATTR_EVENT_DESCRIPTION: "test world"})
GLib.usleep(2000000)
```

**Comment by Zren** [comment]
Timer uses the new `notification.py`, but event starting doesn't.

**Comment by vitovt** [comment]
Yes! It helps me too
> sudo apt install gnome-session-canberra
I have Kde-neon (based on ubuntu 18.04)

I've tried install all console players I know: sox, play, etc ...

Thanks for advice!

**Comment by Zren** [comment]
Should be fixed in v69.
