### ISSUE TITLE
Google Calendar: The requested URL was not found on this server. 

### ISSUE THREAD

**Issue by jackwander** [Zren/plasma-applet-eventcalendar#134]
Everytime i clicked the link
![image](https://user-images.githubusercontent.com/32908963/83338057-10278700-a2f3-11ea-8980-5a3f9709f8cb.png)

this is the result
![image](https://user-images.githubusercontent.com/32908963/83338039-de162500-a2f2-11ea-97e0-70ad06ac9939.png)

**Comment by Zren** [comment]
Right click the link and copy it. Then paste it into your browser. Does that work?

**Comment by jackwander** [comment]
@Zren same result.

**Comment by Zren** [comment]
So, you should be clicking this url:

https://accounts.google.com/o/oauth2/v2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ftasks&response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&client_id=391436299960-o4hchof1u5vq49rdn2nlnlbs295qeqhj.apps.googleusercontent.com

Which should redirect you to a url that looks like this:

https://accounts.google.com/signin/oauth/identifier?scope=...&response_type=code&redirect_uri=...&client_id=...&o2v=...&as=...&flowName=GeneralOAuthFlow

I notice you are instead being redirected to this url that has `/legacy/` in it?!

https://accounts.google.com/signin/oauth/legacy/identifier?authuser=0&part=...

I've no idea why that is happening. What browser + distro are you using? That looks like Chromium?

**Comment by jackwander** [comment]
Hello! Thanks for the link its working now. 

Im using Google Chrome and Kubuntu 18.04.
