### ISSUE TITLE
Multiple font sizes in the same label/line

### ISSUE THREAD

**Issue by YousefH** [Zren/plasma-applet-eventcalendar#14]
Hey I am trying to achieve this:

![image](https://user-images.githubusercontent.com/21363832/39615344-ed0238e0-4fb8-11e8-9d56-770816180696.png)

I am using "Day of week" and "Day of month" applets to achieve that, but prefer to just use one applet. This is what I have on Line 1: `|h:mm AP`.

So this is what I've tried:
* `'<font size="1">'ddd d'</font>' |h:mm AP`
* `'<span style="font-size:6pt;">'ddd d'</span>' |h:mm AP`

The first one seems to work on the preview, but once applied, plasma crash and I had to revert the changes manually inside `~/.config/plasma-org.kde.plasma.desktop-appletsrc `, in order to start up. The second one does not work in the preview nor the actual display, but at least it does not crash plasma.

Regarding the crash, I tried running the applet under `plasmoidviewer` in the hopes I get more info but nothing except:
```
fish: “plasmoidviewer --applet org.kde…” terminated by signal SIGSEGV (Address boundary error)
```

P.S. this test was made with version 51, and 55.

Is it possible to accommodate this feature?

**Comment by YousefH** [comment]
I've done the following changes in [ClockView.qml](https://github.com/Zren/plasma-applet-eventcalendar/blob/f856c881dffac9ca5204a9add6c2833974a3ad81/package/contents/ui/ClockView.qml#L108) and this is the results i got
```qml
textFormat: Text.RichText
//             textFormat: Text.StyledText
//             text: Qt.formatDateTime(clock.currentTime, timeFormat)
            text: Qt.formatDateTime(clock.currentTime, 
                "'<span style=\"font-size:30px;\">'ddd d '</span><span style=\"font-size:60px;\">'|h:mm AP'</span>'"
```

![image](https://user-images.githubusercontent.com/21363832/39662434-a8985cba-50a4-11e8-8b22-52210809203d.png)

However this could probably break the current way of using this tool. I will close this issue and just stick with my previous solution.

**Comment by hockeymikey** [comment]
@YousefH What previous solution? I'm trying to achieve this too.

**Comment by Zren** [comment]
He modified:

`~/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/ClockView.qml`

Then restarted plasma to reload the change:

`kquitapp5 plasmashell; kstart5 plasmashell`

**Comment by hockeymikey** [comment]
@Zren Thanks, kind of a pain but easy enough. Should implement an easier why like the noted above if it's not too trouble. Think it would be a great feature. Xfce's default clock allows that functionality and it's quite handy. Something I really found missing in kde.
