### ISSUE TITLE
Basic Calendar Day of Week Incorrect

### ISSUE THREAD

**Issue by EvanEdwards** [Zren/plasma-applet-eventcalendar#143]
The calendar has the wrong day of week and the grid is drawn incorrectly according to the day of week.  Today is **Friday**, the 10th of July.  The calendar shows **Wednesday** instead.   I have deleted and reinstalled the plasmoid which seems to reset the configuration but the incorrect calendar persists.

![image](https://user-images.githubusercontent.com/2000424/87182651-26d5dc00-c2aa-11ea-8c64-8563fb69e76e.png)

I'm still using the plasmoid for the fantastic agenda, weather, and timer, but the incorrect calendar has confused me a few times now and is obviously a problem.

**Comment by EvanEdwards** [comment]
I'll note that the day of week is correct in the Agenda.

**Comment by EvanEdwards** [comment]
Well, it looks like it is resolved in Master; closing!

**Comment by Zren** [comment]
The logic hasn't changed in years, so I've no idea why updating would fix it. So if you run into the bug again tell me. It could be related to Issue #36.

Here's the relevant code:

* https://github.com/Zren/plasma-applet-eventcalendar/blame/master/package/contents/ui/MonthView.qml#L124
* https://github.com/Zren/plasma-applet-eventcalendar/blame/master/package/contents/ui/MonthView.qml#L224
