### ISSUE TITLE
Google Calandar submit button does nothing

### ISSUE THREAD

**Issue by iboyperson** [Zren/plasma-applet-eventcalendar#147]
After visiting the link, copying the code, and hitting submit a red pop-up comes up saying "HTTP Error 0:". I am guessing google changed their API or something.

P.S. Thanks for this amazing widget!

**Comment by Zren** [comment]
Click the "Refresh" button? Also try relogging as that might work.

HTTP Error 0 means it didn't actually send the HTTP request. Usually means the internet wasn't connected, though it can also mean the Qt HTTP requests derped.

**Comment by iboyperson** [comment]
Update: The "HTTP Error 0:" no longer shows up. Now upon hitting submit nothing seemingly happens. I also tried hitting refresh and also got no results.

**Comment by iboyperson** [comment]
Closing as this now appears to be a duplicate of #108

**Comment by Zren** [comment]
Actually it's probably a duplicate of Issue #137 if it's displaying events but not creating events.

**Comment by iboyperson** [comment]
Looks like you're right. I get this output shortly after hitting submit when running `QT_LOGGING_RULEs="qml.debug=true" plasmawindowed org.kde.plasma.eventcalendar` so it does seem to be a JSON issue

```
qml: HTTP 0 Headers: 

file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/config/GoogleCalendarSession.qml:102: SyntaxError: JSON.parse: Parse error
```

**Comment by Zren** [comment]
No, that's still a `HTTP 0` error. The JSON parsing error is I'm stupidly parsing the data as JSON when there's an error.

**Comment by iboyperson** [comment]
Rats. Sorry about that...
