### ISSUE TITLE
Add option to agenda on the right of the calendar

### ISSUE THREAD

**Issue by lays147** [Zren/plasma-applet-eventcalendar#159]
Hi, 
I didn't update this plasmoid for a while, and today I did, and the agenda is now on the right, and I am used to that be on the left. Could you add that layout option to the Layout menu?

thanks

**Comment by Zren** [comment]
The calendar was deliberately moved to the left as plasma 5.20 is doing the same. It made single column mode better too as now the agenda is now below the month view.

To change it, you'll need to manually edit `PopupView.qml` in the widgets code.

I tried to make a config option to swap the order of the monthview/agenda, but it was rather buggy. To properly fix that bug, I would need to write individual layouts for at least 32 different states to fix it (AgendaOnOff * MonthViewOnOff * MeteogramOnOff * TimerOnOff * SingleOrTwoColumn).

Anyways, you can manually edit:

* `~/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/PopupView.qml`
* https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/PopupView.qml#L244

And change the order to:

    MeteogramView {}
    TimerView {}
    AgendaView {}
    MonthView {}

Eg: The reverse of this: https://github.com/Zren/plasma-applet-eventcalendar/commit/0574d1fb3a1a3265068853c7ddf5262697f46b72#diff-158857febeea53c5e61402ad5558f981

**Comment by mozo78** [comment]
Thank you! I want it on the right too and your guide is precious!

**Comment by lays147** [comment]
@Zren thanks for the response. 
I am going to close this issue. 
Cheers,
