### ISSUE TITLE
Italian language translation

### ISSUE THREAD

**Issue by guidomazzone** [Zren/plasma-applet-eventcalendar#169]
[italian.txt](https://github.com/Zren/plasma-applet-eventcalendar/files/5481359/italian.txt)

I translated Event Calendar into Italian, I hope I complied with pot syntax; I didn't touch "msgid"s containing date formats, for example line 777 msgid "MMMM d, yyyy", because I don't know if I have to.

**Comment by Zren** [comment]
You're suppose to leave `msgid "Event Calendar"` as is and fill out `msgstr ""`. Eg:

```po
#: ../metadata.desktop ../contents/ui/AgendaView.qml ../contents/ui/UpcomingEvents.qml
msgstr "Event Calendar"
msgstr "Calendario Eventi"
```

I can manually fix it though as the order should be the same.

As for timeformats: https://doc.qt.io/qt-5/qml-qtqml-qt.html#formatDateTime-method

* `MMMM d, yyyy` is `November 1, 2020`.
* `yyyy MMM d` is `2020 November 1`

**Comment by Zren** [comment]
Merged in https://github.com/Zren/plasma-applet-eventcalendar/commit/b8d7d6562508e6e56b6308331bb04fa9a83ae8e7
