### ISSUE TITLE
HTTP Error 403: Forbidden (API Quota reached because some users are still running v63)

### ISSUE THREAD

**Issue by summrum** [Zren/plasma-applet-eventcalendar#171]
Hi, I have been using the Event Calendar for around a month without issue. However, this morning I found that all of my GMail calendar entries have disappeared. In the configuration, I see that my GMail account states HTTP Error 403: Forbidden, yet it also states synced under the login section. The Event calendar should have internet access, with weather appearing to still work fine. I have tried removing my account and re-adding, going through the Google confirmation process again, to no avail. I am using Manjaro with plasma 5.20.2, v 70 of Event Calendar. I am unsure exactly when this issue began, but could possibly have been linked to going to plasma 5.20 from 5.19 (upgraded within last few days).

**Comment by summrum** [comment]
I could not find much that appeared particularly useful regarding this issue in my log, only the following:
`plasmashell[1103]: qml: [eventcalendar] onErrorFetchingEvents:  HTTP Error 403: Forbidden
plasmashell[1103]: qml: [eventcalendar] Could not createEvent. Could not find calendarManager for calendarId =  `
I have managed to get the GMail calendar working again by removing the AUR package and usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar, then rebuilding the AUR package.

**Comment by mvastola** [comment]
Can confirmed this also just happened to me. 
I tried to log out and resync, but I got 
```
file:///home/mvastola/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/config/ConfigSerializedString.qml:15: SyntaxError: JSON.parse: Parse error
file:///home/mvastola/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/config/ConfigGoogleCalendar.qml:28: TypeError: Value is undefined and could not be converted to an object
qml: [eventcalendar] onErrorFetchingEvents:  HTTP Error 403: Forbidden
qml: upcomingEvents.onAllDataFetched
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Private/BasicTableView.qml:522:19: QML Component: Cannot create delegate
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Private/BasicTableView.qml: Object or context destroyed during incubation
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:299:25: QML StackView: Binding loop detected for property "height"
```

Not sure if the last few are for this widget or something else.
WIll probably try to recompile since that worked for @summrum .

**Comment by corradopetrelli** [comment]
I have the same problem

**Comment by mvastola** [comment]
Update: Looks like I was on version 65. Just upgraded to 70 from the KDE store and I see design tweaks, but problem isn't fixed.

**Comment by summrum** [comment]
An update from me - the problem has returned this evening, so re-building was apparently only a short term fix. I have not updated or removed any packages on my system to trigger this.

**Comment by corradopetrelli** [comment]
**OS**: Kubuntu 20.04
**Tested version**: 66 and 70
**Problem**: 403 forbidden error when I insert my Google Calendar token.

**Comment by summrum** [comment]
To add my system details:
OS: Manjaro kernel 5.9.6-1 (also occurred with kernel 5.9.3-1)
KDE Plasma: 5.20.2
Event Calendar: 70

**Comment by Zren** [comment]
If you enable debugging:

```
Nov 06 17:34:49 chris-desktop plasmashell[1226]: qml: [eventcalendar:debug] fetchGCalEventsPageResponse [object Object] function() { [native code] } null HTTP Error 403: Forbidden {
                                                   "error": {
                                                     "code": 403,
                                                     "message": "Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:391436299960'.",
                                                     "errors": [
                                                       {
                                                         "message": "Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:391436299960'.",
                                                         "domain": "usageLimits",
                                                         "reason": "rateLimitExceeded"
                                                       }
                                                     ],
                                                     "status": "PERMISSION_DENIED"
                                                   }
                                                 }
                                                  [object Object]
```

**Comment by Zren** [comment]
We probably hit the daily quota. The huge 403 error spike (quota reached) is probably people still using the very broken v63 which constantly fetches events again and again. Users with v64 only fetches events once.

![2020-11-06___17-41-01](https://user-images.githubusercontent.com/416367/98421403-419d3f00-2057-11eb-9531-bd729179194a.png)
![2020-11-06___17-41-28](https://user-images.githubusercontent.com/416367/98421420-4eba2e00-2057-11eb-81ee-e348fba5b302.png)
![2020-11-06___17-41-52](https://user-images.githubusercontent.com/416367/98421452-5d084a00-2057-11eb-91b3-ae5a7f1444b4.png)
![2020-11-06___17-45-59](https://user-images.githubusercontent.com/416367/98421730-02bbb900-2058-11eb-8d82-8baf9fe4da98.png)
![2020-11-06___17-50-24](https://user-images.githubusercontent.com/416367/98421959-93929480-2058-11eb-95a9-9a62a0ae3f3f.png)
![2020-11-06___17-51-51](https://user-images.githubusercontent.com/416367/98422066-c2a90600-2058-11eb-8b27-c99297b4882d.png)
![2020-11-06___17-51-03](https://user-images.githubusercontent.com/416367/98421996-a6a56480-2058-11eb-9694-58777d642100.png)

**Comment by kawaK1320** [comment]
i get 403 when i try to connect with key, it shows "synchronized" but wont show my calendar and when i hit refresh it gives me 403

**Comment by kawaK1320** [comment]
![imagen](https://user-images.githubusercontent.com/67514738/98426872-74582f00-2079-11eb-8250-9b0c2a8a7e63.png)

**Comment by Zren** [comment]
It will not work for 24 hours at least as it hit the API daily quota. You'll need to use the Web Browser.

**Comment by summrum** [comment]
Ok, so this is a Google API request count issue caused by other users using v 63 of the Event Calendar, and should correct itself when the quota resets? Thank you.

**Comment by corradopetrelli** [comment]
Now, It is all ok. Thanks to your elucidation @Zren!

**Comment by Zren** [comment]
Looks like it was working for a few hours today, but reached the daily quota even faster. I may need to reset the api key and push a new version. That would make the the old api key might error 100% of the time though, and I've no idea if the old api key request would contribute to the daily quota. If that is the case, then I would permanently spoil the current api key and I might need to take a bit to request a new one.


![2020-11-07___12-26-54](https://user-images.githubusercontent.com/416367/98447651-888d4200-20f4-11eb-8539-cd77fe30bb41.png)
![2020-11-07___12-34-52](https://user-images.githubusercontent.com/416367/98447793-a4451800-20f5-11eb-8526-5e92d7fc2b90.png)
![2020-11-07___12-41-09](https://user-images.githubusercontent.com/416367/98447901-862be780-20f6-11eb-9d58-155e2b07ef75.png)

**Comment by corradopetrelli** [comment]
As you said, the problem returned unfortunately.... Thanks for your work

**Comment by summrum** [comment]
I can confirm same, and currently not working for me. Thanks for letting us know the cause of the issue so quickly.

**Comment by Zren** [comment]
Apparently I can create multiple OAuth client api keys without needing to "request permissions" to sensitive API again. However, changing the api key requires the user to "logout" and log back in", so I can't roll a new key every version to track which version the userbase is using (would be a cool metric). I could serialize the client key when the user logs in so that I have a estimate of when a user first installed and logged in. Would be interesting to change the key every year to see user retention. Anyways, that's off topic.

I won't be able to fix this. We need to wait for the user using v63 and below to figure out why his computer is slow, or why events aren't showing up and uninstall/update the widget.

**Comment by summrum** [comment]
Ok, thanks again for the information. If v 63 is a year old perhaps we will be waiting a while!

**Comment by Zren** [comment]
* Last time the issue disappeared after 24 hours as we were at just 200k requests per day normally (Issue #85).
* In July I noticed a high error rate in Issue #150.
* We were already at 800k daily requests, so a 20% increase in requests per daily would make us hit out daily limit of 1 million.
* Last week we were at 10 requests / second on average.
* This morning after the daily quota reset, we were at 80 requests / second, dropping down to 20 requests / second over a few hours. A 100% to 800% increase (averaged out to 400% increase).
* So there is 40 requests / second in errors burning though our initial 1 mill request quota.
* 1 request / second * (60 * 60 * 24) = 86400 requests per day
* 1000000 / 86400 = 11.5 requests/second (average maximum per day)

**Comment by summrum** [comment]
Interesting, thank you.

**Comment by corradomella** [comment]
I'm on V68 and suffering the same - sadly recurring - 403 problem that is happening now.
Can't you invalidate and deprecate anything below v63 in all distro repos? Shouldn't that force an update / deletion?
Alternatively, can you create a back channel, somehow, to scream at l folks still on that decrepit version to update?
You must kill off any old install that creates this avalanche effect, or the entire project userbase might vanish.

**Comment by Zren** [comment]
Woke up early to test if the newly created 2nd client id+secret works when the API has quota. It does work.

Changing the client id+secret will require logging out all users. So I might as well merge Pull Request #172 which will do that (and reset a few other settings) as the userbase will need to reconfigure googlecalendar anyways.

I'm planning to *give the users till Wednesday to update**. If there isn't a significant reduction in 403 errors, I'll likely take drastic permanent action.

* I can change/rotate the first client id's "secret" to logout all current users. The question is, will the now permanent 403 errors from v63 users count towards the quota? If I take this method, I think it will as the client id will probably remain the same.
* I can create a 2nd client id+secret, then delete the first client id+secret. Since the first client id no longer exists in the project, the 403 errors might not count towards the quota. This is wishful thinking.

If neither option "hides the 403 (not logged in) errors" then I will be forced to create a new project. I'll probably need to again request permission to the Google Calendar API. I'm hesitant to do this as my Google account would have another project that's performing 2000 error requests / sec which tbh, I wouldn't accept that user.

**Comment by summrum** [comment]
Is it worth contacting Google API support to see what they would advise, before taking any action that has potentially unknown consequences?

**Comment by mvastola** [comment]
@Zren I wouldn't think either of those scenarios would count against the quota. If they did, it would be possible to launch a denial of service attack on any Google Apps client ID (which, by their nature, are public). Also, requests that exceed the quota return "permission denied" and those obviously don't count against the quota.

In any case, I would suggest going ahead with the first option you listed because right now the credentials is basically useless anyway.

**Comment by rithvikvibhu** [comment]
I'm not sure if this has been suggested before, but how about allowing to set our own client id and secret?
Defaulting to the existing project, of course.
People who are comfortable creating a project in the Google API Console can do so, and this will reduce load on the main one's quota, as well as limit interruption to those who use their own project.

Again, this is only as an option to set custom values, but not mandatory for everyone.

**Comment by bradleybowman** [comment]
I was going to suggest allowing user-set API keys as well.  That doesn't fully resolve the issue at hand for the entire userbase (so changing the client secret/new API key will probably be necessary regardless), but it definitely would be nice to have the option.

Though, I doubt there's significant overlap between the users that seek out this thread or would use their own API key yet aren't running an up-to-date version...but it may reduce the default key's load as well.

**Comment by Zren** [comment]
I've noticed that there's still quota left halfway into the error spike (I tested around 1000 requests/sec). So I assume the v63 user is hitting some other error (too many requests per 100sec?). The error spikes drop off for 8-10 hours, so it's definitely just 1 user's PC shutdown for sleep.

> @summrum: Is it worth contacting Google API support to see what they would advise, before taking any action that has potentially unknown consequences?

From what I've heard about Google, I doubt I'd get a timely answer from Google's Customer Support. If it's not on StackOverflow then I'm probably out of luck.

* https://stackoverflow.com/search?q=%5Bgoogle-calendar-api%5D+quota

> I can change/rotate the first client id's "secret" to logout all current users. The question is, will the now permanent 403 errors from v63 users count towards the quota? If I take this method, I think it will as the client id will probably remain the same.

I've just rotated the secret key of the existing api `client_id`. All requests will now error as everyone is using the wrong `client_secret`.

The (counted) errors have dropped already. We'll see what it levels off to after a few hours.

![2020-11-10___15-35-13](https://user-images.githubusercontent.com/416367/98730478-5553e880-236a-11eb-8771-aebfca980e65.png)

> I'm not sure if this has been suggested before, but how about allowing to set our own client id and secret?

You can enable debugging, then go to the Advanced tab to edit the client_id and client_secret. Logout and log back in? However I doubt your client_id will have permission to access a sensitive API like the calendar so it's probably not worth the effort.

**Comment by bradleybowman** [comment]
@Zren I never thought to check there, thanks!

Both the Calendar and Tasks API need to be enabled, and using my own `client_id` and `client_secret` works fine.

**Comment by TheRussianHetzer** [comment]
@Zren I had the same issue, but some hours before your last comment, the sync start working again in my two computers without doing anything.

**Comment by summrum** [comment]
I can confirm that creating my own project for the Google Calendar and entering the `client_id` and `client_secret` in the advanced section after enabling debugging works. Thanks @Zren and @bradleybowman

**Comment by sispus** [comment]
Hi
I can also confirm that using my own client id and secret enabling tasks and calendar apis works.
I tried the original client_id and client_secret (I had copied them somewhere), however they didn't work.

**Comment by corradomella** [comment]
While you're polishing up a new release, can you please change the colour of the text in the Google Calendar login page?
It's not context-aware and both colours are unreadable on the darker window background I'm using.
It's not a colour combo in my colour scheme, I have checked.
Thanks!
![Plasmoid Calendar](https://user-images.githubusercontent.com/15929917/98826466-a082ff80-242d-11eb-8ca1-936e04de2b1b.png)

**Comment by Zren** [comment]
@corradomella: Sure. I could use `theme.posiitveTextColor` and `theme.negativeTextColor` in  
`/home/chris/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/config/ConfigGoogleCalendar.qml`

However color theme's tend to forget to set it. It's also very hard to read as well.

![2020-11-11___10-34-02](https://user-images.githubusercontent.com/416367/98831331-6ef83d00-2409-11eb-8cf0-f8e739dfba50.png)
![2020-11-11___10-34-32](https://user-images.githubusercontent.com/416367/98831375-7e778600-2409-11eb-96b0-6717da124df8.png)


So I decided to take the color themes text color [and tint it](https://doc.qt.io/qt-5/qml-qtqml-qt.html#tint-method) 50% with the positive/negative color.

```qml
function alphaColor(c, a) {
	return Qt.rgba(c.r, c.g, c.b, a)
}
readonly property color readablePositiveTextColor: Qt.tint(Kirigami.Theme.textColor, alphaColor(Kirigami.Theme.positiveTextColor, 0.5))
readonly property color readableNegativeTextColor: Qt.tint(Kirigami.Theme.textColor, alphaColor(Kirigami.Theme.negativeTextColor, 0.5))

```

![2020-11-11___10-31-07](https://user-images.githubusercontent.com/416367/98831007-0741f200-2409-11eb-96fa-1a790b2026b9.png)
![2020-11-11___10-31-40](https://user-images.githubusercontent.com/416367/98831079-19bc2b80-2409-11eb-9b12-9056a54a1186.png)
![2020-11-11___10-32-45](https://user-images.githubusercontent.com/416367/98831188-3f493500-2409-11eb-9e9e-25443b53fb6f.png)
![2020-11-11___10-33-03](https://user-images.githubusercontent.com/416367/98831235-4a03ca00-2409-11eb-9f23-9d81a7fa501c.png)

**Comment by corradomella** [comment]
Hi @Zren and thanks.
I would not usa the colours selected by a scheme in a different shade: they're usually selected to offer the best readability, if - like me - someone is veering off from the default and bothering to go all the way to define a custom scheme.
Happy to test a ß of the plasmoid and give you feedback, because I have the impression that your solution only works on the two extremes of the colour range for the window like in your examples, (off-white and black) but wouldn't be easy to read on my close-to-50% gray background colour.
I know I'm an oddball, but I prefer my windows to be a far darker grey than the almost off-white default on many themes and colour schemes.
If you want to signal the status of the GCal login, why don't you use a semaphore (like a coloured orb) and leave the text to default colour?

**Comment by Zren** [comment]
Beta which installs to `~/.local/share/`. Please uninstall the AUR version installed to `/usr/share/` first if you have it installed.

https://github.com/Zren/plasma-applet-eventcalendar#update-to-github-master

**Comment by RickSlashee** [comment]
great work, perfectly working now!

**Comment by corradomella** [comment]
GCal working now but more glitches with colours.
1. The text colour of the link in the GCal Login page is still a pale cyan that I can't read with my windows background colour.
2. Now, whenever I hover on an agenda item, the whole event block background becomes white.
I'll try with the default Breeze style (I'm using Oxygen) and report back.

**Comment by Zren** [comment]
1. Is your `textColor` blue? Or is your `positiveTextColor` blue? Neither would be default color in Oxygen.
2. I can't fix the QQC2/PlasmaComponent3 buttons which uses `buttonBackgroundColor` on hover. I can fix the agenda item hover color though. I'm not reverting back to QQC1/PlasmaComponents2 buttons as they are deprecated.

**Comment by StevieB-57** [comment]
It seems i might have been using version 61, I hadn't noticed it not working.
However i am now not doing that, version 70 now.
Sorry if this was all my fault! :disappointed: 
Just so i know to check or not in future, does this most excellent widget not update through "Discover"?

**Comment by Zren** [comment]
@StevieB-57: Discover should update it up you installed via "Add New Widget > Get New > Download". However there was a bug where widgets were not updating:

* https://invent.kde.org/plasma/plasma-workspace/-/commit/ce920603ea93ae4abf391d477001bb67cd429ed1

I'm not sure which versions of Plasma had the bug. The commit mentions it's fixed in Plasma 5.20, and a report that it was broken in Plasma 5.19. I don't know if Plasma 5.18 had the bug, or if it got a fix.

**Comment by StevieB-57** [comment]
Ok, thanks, I don't remember how I got the widget originally, but this time i got it with" Add New Widget > Get New"
I have KDE 5.20.3 on KDE Neon and Discover does appear to have some issues updating various themes and icon sets that i got that way too, your link may be a good start to track down what's going there although i appreciate that's not your problem, so thanks for that.

**Comment by INGCRENGIFO** [comment]
He won't let me enter the key


![image](https://user-images.githubusercontent.com/12200313/98953746-112c2980-24cb-11eb-8d20-39d141064467.png)

I have uninstalled event calendar and reinstalled it.

**Comment by TheRussianHetzer** [comment]
I delete my eventcalendar plasmoid and install it using git. After a reboot is now working. Thanks @Zren

**Comment by camendezl** [comment]
I did the same of @TheRussianHetzer and It works now, Thank you very much @Zren!!!

**Comment by Zren** [comment]
Anyone testing the beta should install the final v71 release as there were a few bugs left last night.

https://github.com/Zren/plasma-applet-eventcalendar/compare/55ae1bd..v71

I will be closing this issue as people are more likely to search for the HTTP 401 Unauthorized error now (Issue #177).
