### ISSUE TITLE
Latte-Dock crashes when "Configure Evet Calendar..." is clicked

### ISSUE THREAD

**Issue by Sadi58** [Zren/plasma-applet-eventcalendar#175]
I prefer using Latte-Dock for panel and dock instead of the default KDE panel.
However, after upgrading from Kubuntu 20.04 to 20.10 it has become impossible to use the Event Calendar.
After installing and adding it to the panel (Add Widgets > Get New Widgets > Download New Plasma Widgets), Latte-Dock crashes and reloads as soon as "Configure Evet Calendar..." is clicked.
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2

**Comment by Zren** [comment]
Sounds like a duplicate of Issue #167. Looks like I need to disable the sfx playback test as even Kubuntu is having problems with QtMultimedia (not just OpenSuse).

**Comment by Sadi58** [comment]
@Zren Oh, sorry, I didn't see that. And the same fix worked for me, too. Thanks!
