### ISSUE TITLE
Cannot create event using widget on google calendar

### ISSUE THREAD

**Issue by sispus** [Zren/plasma-applet-eventcalendar#185]
Hi,
I just upgrade to v71 from repo on manjaro kde and thank you for great work of you. Eventcalendar now connects and syncs successfully to google calendar. However I cannot add a new event from the widget. Adding an event i.e. "9am-5pm Work" from the widgets window does nothing. When I refresh the calendar using refresh button at the bottom right the event just added disappears. What can I do to fix it?

**Comment by Zren** [comment]
Adding new events works for me.

Did you restart after updating? The config window can load the latest code after updating, however the widget in the panel still needs to be reloaded.

**Comment by sispus** [comment]
yes, I did restart. Now I restart again and show a "HTTP error 0" warning at the bottom of the widget panel. Also it cannot fetch the weather: "XMLHttpRequest.onerror(undefined)"  I tried logout and relogin to google. I can successfully submit the code, get the calendar list and sync. Howeer cannot add a new event. The warning messages are still exist.

**Comment by Zren** [comment]
HTTP 0 is Could Not Connect to internet usually. I need to detect when the internet is available. The weather should work after hitting refresh manually as suggested in Issue #144.

Not sure why events are loaded correctly, but quickAdd fails though.

**Comment by sispus** [comment]
If the refresh is the button at the bottom of the panel, it cannot fix the weather. I have to reenter the city code in the configuration window. Maybe my wifi connection is late for eventcalendar to load weather info since this problem doesn't appear every restart, sometimes it works.

**Comment by sispus** [comment]
I removed the widget and add it again. Its working now.
