### ISSUE TITLE
Meteogram only settings not retained between reboots

### ISSUE THREAD

**Issue by gbcox** [Zren/plasma-applet-eventcalendar#200]
If you set Meteogram to show, but not the timer, it works upon initial configuration.  If you then reboot, the meteogram display is missing.  There is a white space where the meteogram is suppose to be.  To get it to return properly, you need to go into settings and deselect and then reselect.

**Comment by Zren** [comment]
Sounds more like an error when fetching the weather data than it not recognizing the config, otherwise the text asking you to configure it would appear.

**Comment by gbcox** [comment]
Thanks for the quick reply.  I've tested several times this afternoon and it so far is not reproducible so perhaps it was something wonky at the time.   I'm closing this report.
