### ISSUE TITLE
Yellow Tooltip regarding connection perpetually showing.

### ISSUE THREAD

**Issue by JackDinn** [Zren/plasma-applet-eventcalendar#205]
For the last couple of updates to event calendar im getting a yellow tooltip type pop-up warning that remains up perpetually unless i click to close it. It shows up every time i wake the system from suspend.

`System:    Kernel: 5.4.80-2-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0 Desktop: KDE Plasma 5.20.4 Distro: Manjaro Linux `
`[2020-12-22T12:04:09+0000] [ALPM] upgraded plasma5-applets-eventcalendar (71-1 -> 72-1)`

![ZZ_20201223-073443](https://user-images.githubusercontent.com/5557560/102972093-6c056780-44f2-11eb-8af1-72ea65a2d8e8.png)

**Comment by Zren** [comment]
When it wakes up, the network won't be ready so it errors. This is similar to users with WiFi not having a connection when logging in (Issue #113). I've written some code to make the weather+event data refresh automatically when the network connects, but I still need to determine if:

* I should always hide HTTP Error 0 messages if there's no internet connection and only show them when it detects there is a network connection (and something is screwy with QML HTTP requests).
* Only show HTTP Error 0 messages after a 10 second timeout of waiting for the internet connection.

**Comment by JackDinn** [comment]
I mean i wouldn't mind at all that i get these error messages as thats what they are supposed to do, it's just that they remain visible permanently, they do not close after any amount of time unless i manually click/close them.
 
It could be a linux DE (kde in this case) problem, but im not sure as other tooltips and notifications come up and disappear fine.

**Comment by Tunas1337** [comment]
I have this same issue. The problem is that yes, it doesn't disappear on its own. I think the most elegant solution which would also be the easiest to implement would be an (X) button on the tooltip to dismiss it manually; I can live with having to do this once every boot-up, as long as I _am_ given the ability to do it.

**Comment by JackDinn** [comment]
I was going to say, it does have a button. It's just that there's not a whole lot of point to a button if the tooltip is always back again. I'm not going to click it every time i look at my calendar since it does not interfere with anything particularly so it just gets left there permanently.

**Comment by Zren** [comment]
v73 should automatically close the http 0 error when the network reconnects.
