### ISSUE TITLE
Feature request: 24 Hr Clock in tool tips.

### ISSUE THREAD

**Issue by TaliesinEmrys** [Zren/plasma-applet-eventcalendar#207]
Hello,
If at all possible a setting where 24 hour clock could be chosen for tool tip times, (timezones), would be appreciated.

This would make time format displays consistent for those, (like myself), who prefer 24 hr clock.

That aside, this is the best time / calendar app from my perspective.

Thank you for your work and effort.

Cheers.

**Comment by C0rn3j** [comment]
![image](https://user-images.githubusercontent.com/1641362/113679763-6bb76380-96c0-11eb-872a-f2f0bc11950c.png)

Already a thing, I assume your LC_TIME(if even set) is not using the format you want.

https://wiki.archlinux.org/index.php/Locale#LC_TIME:_date_and_time_format

**Comment by TaliesinEmrys** [comment]
Cool thankyou,
I did have LC_TIME set, but wasn't aware there were different options for my timezone.
I've now changed it for the option that utilises 24 Hr clock.

Cheers.

**Comment by C0rn3j** [comment]
Np, might want to close the issue then.

**Comment by Zren** [comment]
The issue was left open because we support a custom timeformat which can specifiy `ap` to make it 12h. The tooltip format needs to be based off of that not the default locale's format.

**Comment by TaliesinEmrys** [comment]
No worries.
I missed that.
Cheers.
