### ISSUE TITLE
Network management error

### ISSUE THREAD

**Issue by Storm-Engineer** [Zren/plasma-applet-eventcalendar#214]
I have just upgraded my system after a while and now EventCalendar won't load, displaying only the following error:

`Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/main.qml:25:2: Type NetworkMonitor unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/NetworkMonitor.qml:2:1: module "org.kde.plasma.networkmanagement" is not installed`

The package `networkmanager` is installed and up to date. In the settings panel everything under the Network tab looks normal. I made sure that `NetworkManager.service` is running.

Arch Linux, fully updated

**Comment by Zren** [comment]
Duplicate of #212.
