### ISSUE TITLE
Trouble Fetching Weather

### ISSUE THREAD

**Issue by skalogerakis** [Zren/plasma-applet-eventcalendar#216]
I am currently facing an annoying issue every time I reboot my pc. I get an "fetching weather error(XMLHttpRequest.onerror(undefined))" for a few minutes after the pc launches, but after a while I can see the weather forecast as expected. What exactly causes this error and is there a way to solve it?

Kubuntu 20.10
KDE Plasma 5.19.5

**Comment by gmm96** [comment]
Your computer may initialize kde plasmashell and all the widgets before the wifi connection is set up while booting up. This is also my case as I explain in this issue.

https://github.com/Zren/plasma-applet-eventcalendar/issues/218
