### ISSUE TITLE
Widget can't connect to google account

### ISSUE THREAD

**Issue by nntndfrk** [Zren/plasma-applet-eventcalendar#224]
![Screenshot_20210228_172203](https://user-images.githubusercontent.com/2458463/109423845-c7b80980-79e9-11eb-9b39-f5bae3d84c35.png)

Operating System: KDE neon 5.21
KDE Plasma Version: 5.21.1
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-66-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G
Memory: 6.7 ГіБ of RAM
Graphics Processor: AMD KAVERI

**Comment by Zren** [comment]
What version of Event Calendar?

**Comment by nntndfrk** [comment]
![Screenshot_20210302_213705](https://user-images.githubusercontent.com/2458463/109704645-823d3d00-7b9f-11eb-9bed-d1289dd18883.png)
Thank you for response. Look like it's 69 version in KDE neon 5.21.

**Comment by Zren** [comment]
You need to install v71.

https://github.com/Zren/plasma-applet-eventcalendar/blob/master/Changelog.md#v71---november-13-2020

**Comment by nntndfrk** [comment]
I installed v73 from pling-store and it's work well. Thank you!
