### ISSUE TITLE
Dependency on plasma-nm is not mentioned in documentation

### ISSUE THREAD

**Issue by MatthewForrester** [Zren/plasma-applet-eventcalendar#227]
I am using Ubuntu 20.04.2 LTS with KDE Plasma 5.18.5 and KDE Frameworks 5.68.0.

I installed _Event Calendar_ for the first time following the very helpful instructions in the "Install via KDE'" section of the repo home page.

When I right-clicked on the new icon in my Panel, I got the following error message:
`Error loading QML file: file:///home/linmanfu/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/main.qml:25:2: Type NetworkMonitor unavailable
file:///home/linmanfu/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/NetworkMonitor.qml:2:1: module "org.kde.plasma.networkmanagement" is not installed`

Some online searches suggested that this indicates that _Event Calendar_ is dependent on the KDE [Network Management](https://userbase.kde.org/NetworkManagement) package. In Ubuntu repos, this is the _[plasma-nm](https://packages.ubuntu.com/search?keywords=plasma-nm&searchon=names&suite=all&section=all)_ package. I installed this with _apt_ and the problem corrected itself after a reboot.

Issue #212 confirms this analysis and indicates that you expected all distributions would have _plasma-nm_ installed.

I did not have _plasma-nm_ installed and a little background may help to understand why it may not be sensible to assume that it is present. The Ubuntu repos have two ways to install KDE Plasma. One is the _[kubuntu-desktop](https://packages.ubuntu.com/focal/kubuntu-desktop)_ metapackage, which installs not only KDE Plasma but also the full KDE suite: Konversation, KMail, etc. As the same suggests, this is equivalent to Kubuntu and it includes _plasma-nm_. The other is the _[kde-plasma-desktop](https://packages.ubuntu.com/focal/kde-plasma-desktop)_ metapackage which only installs Plasma, the core KDE/Qt libraries, and [a few core applications](https://packages.ubuntu.com/focal/kde-baseapps) (Dolphin and Konqueror). It does **not** install _plasma-nm_. This is what I use. §

I had a glance at the situation for some other distros. I could only find the smaller _plasma-desktop_ package in the Debian repos, so it is likely that other Debian-based distros will offer Plasma without _plasma-nm_. Arch [does](https://archlinux.org/packages/extra/x86_64/plasma-nm/) have it as a dependency for its _plasma-desktop_ metapackage. I am not very familiar with the RPM world, but Fedora has an up-to-date _plasma-nm_ package that [is apparently not a dependency](https://src.fedoraproject.org/rpms/plasma-desktop/blob/rawhide/f/plasma-desktop.spec) for its _plasma-desktop_ package.

I think that this is primarily a documentation issue. The installation instructions should state that KDE Network Manager is a dependency requirement and that this package is called _plasma-nm_ in many (most?) distros.

Thank you to everyone who contributed to this widget!

§ If you are puzzled why anyone would ever choose _plasma-desktop_, it's because I am tentatively migrating from Gnome. I do not want Gnome Keyring and KWallet clashing during the migration. If I continue with Plasma, then I will still be mostly using LibreOffice, Firefox, and other non-KDE apps.

**Comment by Zren** [comment]
It was never documented since I was going to make it optional but dragged my ass over implemnting it.
