### ISSUE TITLE
Feature request: Copy current date to clipboard via click/doubleclick on calendar item

### ISSUE THREAD

**Issue by MurzNN** [Zren/plasma-applet-eventcalendar#28]
It is often necessary to insert a certain date in the text. Will be good to have a feature in Event Calendar widget for quick copy to clipboard selected date in format, pre-defined by user, via click/doubleclick/rightclick on calendar item.

**Comment by Zren** [comment]
Assuming `ClipboardMenu` is part of `import org.kde.plasma.private.digitalclock 1.0`, then we only need:

```
import org.kde.plasma.private.digitalclock 1.0 as DigitalClock

Item {
    Component.onCompleted: {
        plasmoid.setAction("clipboard", i18n("Copy to Clipboard"), "edit-copy");
        DigitalClock.ClipboardMenu.setupMenu(plasmoid.action("clipboard"));
    }
}
```

* https://invent.kde.org/plasma/plasma-workspace/-/blob/master/applets/digital-clock/package/contents/ui/main.qml#L133
* https://invent.kde.org/plasma/plasma-workspace/-/blob/master/applets/digital-clock/plugin/digitalclockplugin.cpp#L50

**Comment by Zren** [comment]
Ah, we'd also need to set `DigitalClock.ClipboardMenu.currentDate = ...` during the contextmenu's AboutToShow event.

https://invent.kde.org/plasma/plasma-workspace/-/blob/master/applets/digital-clock/package/contents/ui/DigitalClock.qml#L76-82

Not sure why that connection is in the compact representation file instead of `main.qml`.

**Comment by Zren** [comment]
Note that this requires Plasma 5.13, so I should make sure to bump the min plasma version required the the zipped filename.

https://invent.kde.org/plasma/plasma-workspace/-/commit/ffa23acf440b0a162a9458f06622d2c98ed3f80c
