### ISSUE TITLE
Add KOrganizer support

### ISSUE THREAD

**Issue by renyuneyun** [Zren/plasma-applet-eventcalendar#3]
It seems this plugin is handling calendar itself. However, KDE already provides KOrganizer as an aggregation of calendars (not only google calendar).

It would be nice to have integration with KOrganizer. I.e. can read calendar events from KOrganizer.

**Comment by renyuneyun** [comment]
My fault. I should notice the other issue (#2) first...

Same as Zren/plasma-applets#12. Closed.

**Comment by Zren** [comment]
Try out v54.
