### ISSUE TITLE
OpenWeatherMap City Selector needs to be updated

### ISSUE THREAD

**Issue by Zren** [Zren/plasma-applet-eventcalendar#31]
https://openweathermap.org/help/city_list.txt was removed. We now need to download the city list from http://bulk.openweathermap.org/sample/ as a `.json.gz`. I'm uncertain if this can be done with just javascript. I might have to forgo downloading a list, and instead just search for a city using the API endpoint.

**Comment by battaglia01** [comment]
When you say you're not certain if this can be done using just javascript, I assume you mean specifically using gzip?

**Comment by Zren** [comment]
Fixed in v59
