### ISSUE TITLE
Uppercase in formating?

### ISSUE THREAD

**Issue by babydickdanilko** [Zren/plasma-applet-eventcalendar#311]
How is it possible to do uppercase in text formatting? And is it even possible?

**Comment by Zren** [comment]
You'll need to edit the widget code directly.

* `~/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/ClockView.qml`
* https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/ClockView.qml#L109

For both `timeLabel1` and `timeLabel2`:

Change `text: Qt.formatDateTime(clock.currentTime, timeFormat)`  
To `text: Qt.formatDateTime(clock.currentTime, timeFormat).toUpperCase()`

Also, we need to edit the "width calculation" in `TimeFormatSizeHelper.qml`.

Add `.toUpperCase()` after the two `Qt.formatDateTime(date, widestTimeFormat)` calls in 

* `~/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/TimeFormatSizeHelper.qml`
* https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/TimeFormatSizeHelper.qml#L46

**Comment by babydickdanilko** [comment]
Thanks for the detailed and fast response.
