### ISSUE TITLE
feature request -- option to change first day of week

### ISSUE THREAD

**Issue by jedd** [Zren/plasma-applet-eventcalendar#32]
Greetings!

Love the applet - a vast improvement over the stock, and a delight to look at.

Could I please ask for an option to set first day of week - in my locale (AU) we use Monday as the first day of the week, and have Sat/Sun adjacent at the right side usually.

Thanks again for a great tool.

**Comment by Zren** [comment]
Will be in v60.

**Comment by sudhirkhanger** [comment]
@Zren is this feature already implemented in the Event Calendar? Where it might be? I am unable to find it in version 55.
