### ISSUE TITLE
Allow more than two lines of formatted date display

### ISSUE THREAD

**Issue by alxpettit** [Zren/plasma-applet-eventcalendar#340]
In use cases where the panel is positioned vertically, it can be useful to separate date and time information into more lines, but the configuration panel only allows a maximum of two. The ideal would be to have a `+` button that allows an indefinite number. :)
![image](https://user-images.githubusercontent.com/28266167/208557490-b78d32b3-cca4-4490-bfc4-b393e9db773f.png)

**Comment by Zren** [comment]
You can put `'<br>'` (don't forget the single quotes) to add an extra line. Make sure to add more space in the fixed height setting too.

https://doc.qt.io/qt-5/qml-qtquick-text.html#textFormat-prop

The clock formatting is complicated enough that I don't really want to officially support up to 10 lines of text...

**Comment by alxpettit** [comment]
Ah, gotcha thanks
