### ISSUE TITLE
Google Calendar support requires clicking the clock

### ISSUE THREAD

**Issue by atenie** [Zren/plasma-applet-eventcalendar#40]
It might seem like an odd thing to request, but I am not receiving notifications from Google Calendar events if I am not clicking the clock on my desktop.

Using 5.6, on Kubuntu 18.04.

**Comment by atenie** [comment]
As in KOrganizer no longer displays notifications unless I open Event Calendar.

**Comment by Zren** [comment]
Oh KDE PIM events, which are synced to GCal via KOrganizer. Gotcha.

**Comment by Zren** [comment]
Should be fixed now.
