### ISSUE TITLE
Option for 12-hour time without showing AM/PM?

### ISSUE THREAD

**Issue by daboross** [Zren/plasma-applet-eventcalendar#47]
Hi,

Posting this here since I couldn't think of a better place to put it.

Is there any way to have a time like `8:24` shown in the upper bar in 12-hour time and without an `am`/`pm` marker? I have this configured on my phone and I really miss it in KDE with this applet.

My rational for choosing this format is that I generally know whether it's morning or evening just from the time of day, and when I'm looking at the clock I'm looking for an exact time. I don't _need_ `am` or `pm` markers and `8:24pm` is significantly less small and nice looking than `8:24`.

I realize this is a bit of a niche feature, but it would be quite nice if it could be included. Thanks.

**Comment by Zren** [comment]
Use `h:mm'<'AP'>'`. It's sort of a hack I've been using. Basically QML text sees the `<am>` and `<pm>` tags but doesn't recognize them so it ignores them.

![](https://i.imgur.com/KcOa7VU.png)

**Comment by daboross** [comment]
Thanks!

**Comment by Zren** [comment]
Ah makes sense that it needs at least one valid tag to switch from "raw text" mode to "rich text" mode.

http://doc.qt.io/qt-5/qml-qtquick-text.html#textFormat-prop

**Comment by AndydeCleyre** [comment]
Maybe include this workaround in the README?
