### ISSUE TITLE
Incorrect link for city list

### ISSUE THREAD

**Issue by mzfr** [Zren/plasma-applet-eventcalendar#50]
The link (https://openweathermap.org/help/city_list.txt) that is given in the `Select city` section is not correct that is why nothing is displayed.

**Comment by Zren** [comment]
This was fixed in v59: https://github.com/Zren/plasma-applet-eventcalendar/commit/1b47a583f17b8735a4deb80770ee9402cd72a66f

![](https://i.imgur.com/o8J0XPl.png)

**Comment by Zren** [comment]
Duplicate of #31
