### ISSUE TITLE
space/font configuration problem

### ISSUE THREAD

**Issue by alekksander** [Zren/plasma-applet-eventcalendar#6]
i cannot get it to display nice and tidy as default clock with date can. 
![screenshot_20180317_133701](https://user-images.githubusercontent.com/3148302/37555536-dfa9cd3e-29e8-11e8-9629-322827075489.png)
i think the problem is too big spacer between date and clock. there is no set of setting to fix that.

**Comment by Zren** [comment]
Hmmm, I forget why this is happening. The area to draw in is the same more or less. It's just that the "line height" appears to have padding in my widget while digitalclock does.

![](https://i.imgur.com/DVv7fgA.png)

* https://github.com/KDE/plasma-workspace/blob/master/applets/digital-clock/package/contents/ui/DigitalClock.qml#L473
* https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/ClockView.qml#L56
* https://github.com/KDE/plasma-framework/blob/master/src/declarativeimports/plasmacomponents/qml/Label.qml
* http://doc.qt.io/qt-5/qml-qtquick-text.html

**Comment by Zren** [comment]
Ah... looks like DigitalClock doesn't apply `fontSizeMode: Text.VerticalFit` to the Labels.

* The red outline is the area dedicated to the Label.
* The yellow outline is the actual drawn area the text uses.

The left is digitalclock, the right is eventcalendar.

![](https://i.imgur.com/Gt8UyYG.png)

* I still need to test vertical panels.
* I still need to compare when tested inside of a panel instead of using plasmoidviewer.

**Comment by Zren** [comment]
As for controlling the spacing... hmmm. I could probably just set the `Column.spacing`. I'll need to modify the "available height too.

I've made it a "ratio" of the widget's height, rather than a fixed pixel size.

Video: https://streamable.com/m3kv0

**Comment by Zren** [comment]
A side effect of "fixing" the spacing, is that we'll now have the same bug as digitalclock, where the text is too big.

![](https://i.imgur.com/bsVM66L.png)

This means I'll have to change the defaults somehow. I'll probably grab the constants that digitalclock is using for the default "scale to fit".

**Comment by Zren** [comment]
![](https://i.imgur.com/njH91oO.png)

Reminder: Another user requested this on the store page, so update them when you fix this.

**Comment by Zren** [comment]
Also, it seems that I need to remove the space between the "top" and the "ascent", and also the space between the descent and "bottom".

https://stackoverflow.com/questions/27631736/meaning-of-top-ascent-baseline-descent-bottom-and-leading-in-androids-font

![](https://i.stack.imgur.com/LwZJF.png)

QML doesn't seem to have a way to do that, thus the workarounds.
