### ISSUE TITLE
Segfault on Plasma 5.14.90 (Plasma 5.15) - Ubuntu 19.04 Daily

### ISSUE THREAD

**Issue by feren** [Zren/plasma-applet-eventcalendar#61]
In Plasma version 5.14.90 on Ubuntu 19.04 'Disco Dingo' so far, the usage of Event Calendar v61 causes 'plasmashell' to immediately segmentation fault upon trying to load the widget, with a very very rare chance of a segmentation fault not happening and the applet therefore working just fine.

This bug couldn't be produced on Plasma version 5.14 from Ubuntu 18.10 + Kubuntu Backports, where it would instead work 100% of the time fine.

The output from 'plasmashell' when trying to load the applet and segmentation fault-ing is as follows:
```
adding "org.kde.plasma.eventcalendar"
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the -global-isel-abort option: may only occur zero or one times!
KCrash: Attempting to start /usr/bin/plasmashell from kdeinit
sock_file=/run/user/1000/kdeinit5__0
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = plasmashell path = /usr/bin pid = 19258
KCrash: Arguments: /usr/bin/plasmashell 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
QSocketNotifier: Invalid socket 8 and type 'Read', disabling...
QSocketNotifier: Invalid socket 25 and type 'Read', disabling...
QSocketNotifier: Invalid socket 9 and type 'Read', disabling...

[1]+  Stopped                 plasmashell
```

This might not be related to your applet (it only started happening today for me after some updates being installed yesterday), but just in case it is, better to report it now than leave it be.

**Comment by Zren** [comment]
There was an opensuse bug too I think (#26), I couldn't reproduce it then though. I'll try testing SUSE again unless you know a LiveCD I can test this on.

**Comment by feren** [comment]
@Zren Is there a Plasma Version of the Ubuntu 19.04 Daily ISOs? If not then you can always install kubuntu-full to a 19.04 Daily ISO Install...

**Comment by Zren** [comment]
My normal way to test is using KDE Neon's gitunstable which is using 18.04, but this sounds distro specific.

Kubuntu has a daily ISO it seems. http://cdimage.ubuntu.com/kubuntu/daily-live/current/

I'll try the `kubuntu-full` way with the [ubuntu daily iso](http://cdimage.ubuntu.com/daily-live/current/) after if I can't reproduce it with Kubuntu or Suse.

**Comment by feren** [comment]
![image](https://user-images.githubusercontent.com/11057934/52526812-b4c52600-2cb6-11e9-8648-12c6443e8b0d.png)

**Comment by Zren** [comment]
Testing the kubuntu disco daily LiveCD, I can't reproduce.

![2019-02-09___23-21-00](https://user-images.githubusercontent.com/416367/52529591-54d47c80-2cc2-11e9-9033-ee327eda5cba.png)

The recursion error... it's possible that my "keep the date always visible in the agenda" when scrolling could be causing issues. I'll disable the feature in v62 and have you test that.

**Comment by feren** [comment]
Alright, managed to get some good RnG with Plasmashell and found out something interesting:
- During all the times Plasmashell doesn't crash immediately while the applet is active, it ALWAYS then segmentation faults when going into the 'Events' page of Event Calendar Settings, and NOT any others page of its configuration window.

**Comment by Zren** [comment]
Wait, it's randomly crashing. Okay, I try restarting plasmashell a few times in my LiveCD test.

>  'Events' page of Event Calendar Settings

Hmmm. It's quite possible that it's not liking that I select the "Holidays" plugin by default. When the widget doesn't crash immediately, did you see the "Holiday" events in the agenda? Or does it not list any holidays?

https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/config/main.xml#L179-L182

```
<entry name="enabledCalendarPlugins" type="StringList">
	<label>A list of plugins where additional calendar event data can be sourced.</label>
	<default>/usr/lib/x86_64-linux-gnu/qt5/plugins/plasmacalendarplugins/holidaysevents.so</default>
</entry>
```

I recently found out that Arch/Manjaro puts the file in a different filepath:

* Kubuntu / KDE Neon: `/usr/lib/x86_64-linux-gnu/qt5/plugins/plasmacalendarplugins/holidaysevents.so`
* Manjaro: `/usr/lib/qt/plugins/plasmacalendarplugins/holidaysevents.so`

I wonder if it's segfaulting when trying to load the wrong filepath.

What's the location of qt5 in your test ISO?

Does it still crash if you edit `~/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/config/main.xml` and change `enabledCalendarPlugins`'s default to an empty list `<default></default>`.

I've known that I needed to change my method of pre-selecting the default `holidaysevents.so`, but it wasn't causing any crashes on Manjaro, I was just getting these `plasmashell` terminal logs:

```
Could not create Plasma Calendar Plugin:  "/usr/lib/x86_64-linux-gnu/qt5/plugins/plasmacalendarplugins/holidaysevents.so"
"The shared library was not found."
Could not create Plasma Calendar Plugin:  "/usr/lib/x86_64-linux-gnu/qt5/plugins/plasmacalendarplugins/holidaysevents.so"
"The shared library was not found."
```

How are you testing? With a Kubuntu LiveCD in virtualbox?

Here's a video of me restarting plasmashell 3 times trying to trigger the crash, I did not experience a crash.
https://www.youtube.com/watch?v=1is484RZTRI

**Comment by feren** [comment]
I'm using a slightly different variation of Kubuntu in the form of Feren OS Next but using the Ubuntu 19.04 Repositories. It shouldn't be too different from Kubuntu itself otherwise, though...
1. Yes, there is Events when it works in the rare occasion
2. Yep it's where it is in Kubuntu
3. Yes it still crashes
4. Using it on real hardware with an AMD A9 7th Gen GPU

I'll go get a Kubuntu Daily install to check it isn't just my packages for Feren OS Next on top of Kubuntu and such that are causing this issue...

**Comment by feren** [comment]
Closing this because of I've now installed a new build of Feren OS Next that uses the KDE Neon PPA on 18.04 and doesn't have this segfault issue.
