### ISSUE TITLE
[new feature] show event location in agenda

### ISSUE THREAD

**Issue by Core00077** [Zren/plasma-applet-eventcalendar#68]
Would be awesome if there is an option for showing the location of an event on agenda.

> description display is already good enough to do the job though, a location option would be awesome for not messing up with the function and meaning of description.

**Comment by Zren** [comment]
I think I'll go with the more condensed `2pm - 3pm at Location` over putting it on it's own row. This is what the Google Calendar Android app does with their "Schedule" view. Event Flow Calendar uses `2 - 3 PM | School` which is probably even more condensed than the translation for "at" in every language.

![2019-10-04___20-06-36](https://user-images.githubusercontent.com/416367/66246485-79aeb180-e6e2-11e9-8ae4-58fb7277e6f9.png)

I'll still need to use the Icon+TextField view for editing the event location.

**Comment by Core00077** [comment]
Awesome! Looking forward to it. Closing this issue when it's done.

**Comment by Zren** [comment]
v64 is released with location feature.
