### ISSUE TITLE
Dark style in configuration display unproperly

### ISSUE THREAD

**Issue by Core00077** [Zren/plasma-applet-eventcalendar#70]
I am translating this nice plugin when it come to me that all this subtitles are black in my dark theme. which is a little bit unclear.
I didn't even notice this till I'm translating the widget and wondering where it is. Then I found it in the picture.
![image](https://user-images.githubusercontent.com/28624864/56257183-f5e61600-60fd-11e9-8ee1-8771b6921d09.png)

Hoping it to be fixed. (maybe just follow the theme will do the trick)

**Comment by Zren** [comment]
Ah, that's caused by `syspal.text` no longer existing in a newer version of Plasma (I wasn't suppose to be using that variable), so it it was an invalid color and fell back to black. I'll use the `Kirigami.Theme.textColor` in the next version. Thanks for noticing (I use a light theme obviously).
