### ISSUE TITLE
[TYPO] Scoll Up instead of Scroll Up

### ISSUE THREAD

**Issue by herzenschein** [Zren/plasma-applet-eventcalendar#77]
Just noticed this typo in the English version while updating the pt_BR .po file.

https://github.com/Zren/plasma-applet-eventcalendar/blob/c91a8d171ec7b44ce85c6dcc48e0c7c9293bac41/package/contents/ui/config/ConfigGeneral.qml#L396

**Comment by Zren** [comment]
Ah! It looks like that typo has been there for a while. It was in Win7ShowDesktop as well which I wrote before EventCalendar back around 2016.
