### ISSUE TITLE
KMix volume control doesn't work

### ISSUE THREAD

**Issue by alekksander** [Zren/plasma-applet-eventcalendar#8]
default entries are:
`qdbus org.kde.kglobalaccel /component/kmix invokeShortcut "increase_volume"`
`qdbus org.kde.kglobalaccel /component/kmix invokeShortcut "decrease_volume"`
but that doesn't work. not sure if it's eventcalendar issue (sorry if not). any way to diagnose the issue?

**Comment by Zren** [comment]
Do the commands work if you enter them in the terminal? Does the `Volume (No UI) (amixer)` commands work?

**Comment by alekksander** [comment]
`aleksander@B75TN:~$ qdbus org.kde.kglobalaccel /component/kmix invokeShortcut "increase_volume"
qdbus: could not open config file '/usr/lib/x86_64-linux-gnu/qt-default/qtchooser//default.conf': No such file or directory
`

**Comment by alekksander** [comment]
`amixer set PCM 3%+` and `amixer set PCM 3%-` works fine from eventcalendar, i made a bad copy paste. my fault.

**Comment by Zren** [comment]
It seems the reason why qdbus isn't working, is because it's unable to tell which version of Qt to use by default. Older apps might need Qt 4, while Plasma uses Qt 5. I remember this happening a long time ago, but forget how I fixed it.

Maybe try googling the `qtchooser` command?

**Comment by alekksander** [comment]
amixer set PCM is a walkaround in this case, i will remember about qtchooser next time i stuble on such problem. thanks!
