### ISSUE TITLE
Turkish translation!

### ISSUE THREAD

**Issue by eggsywashere** [Zren/plasma-applet-eventcalendar#82]
Hey, I just made the Turkish full translation.
[tr.zip](https://github.com/Zren/plasma-applet-eventcalendar/files/3245129/tr.zip)

**Comment by eggsywashere** [comment]
I don't know how this happened, I haven't used any "Ö"s in the translation file but ![this]((https://user-images.githubusercontent.com/13917975/58766384-a3b26480-8586-11e9-9b2e-b3254ffa1fb2.png)) happened.

**Comment by Zren** [comment]
You translated the full month `MMMM` (September) as `AAAA` which was parsed by Qt as the `AP` keyword that represents AM/PM.

https://doc.qt.io/qt-5/qml-qtqml-qt.html#formatDateTime-method

```
#: ../contents/ui/MonthView.qml:363
msgctxt "calendar title format for current month"
msgid "MMMM d, yyyy"
msgstr "AAAA g, yyyy"

#: ../contents/ui/MonthView.qml:367
msgctxt "calendar title format for other months of current year"
msgid "MMMM"
msgstr "AAAA"

#: ../contents/ui/MonthView.qml:370
msgctxt "calendar title format for months not from current year"
msgid "MMMM, yyyy"
msgstr "AAAA, yyyy"
```

![2019-06-02___18-48-02](https://user-images.githubusercontent.com/416367/58768298-20354b00-8567-11e9-9d75-39cf5d1c0fe1.png)

**Comment by eggsywashere** [comment]
Oh, I didn't know that. Are you going to fix those or you want me to do it and re-upload here?

**Comment by Zren** [comment]
I'll fix them, no worries.

**Comment by eggsywashere** [comment]
Alright, thank you <3
