### ISSUE TITLE
what are this http.so process

### ISSUE THREAD

**Issue by Cherkah** [Zren/plasma-applet-eventcalendar#83]
hi! thanks a lot for this amazing app :)

the only problem i'm facing on is to undrstand why this 2 process "http.so" not  use 443 port but the 80 one?

`$ netstat -lapute && sockstat -4 -l`
give me
`.
.
.
tcp        0      0 192.168.1.47:33778      82.196.7.246:http       ESTABLISHED MEAK
[kdeinit5] http .....
.
.
.
MEAK    http.so    22890    tcp4   192.168.1.47:33776      82.196.7.246:80   ESTABLISHED`

so, as this applet do not deliver only weather's statement (PIM &G;calendar) , could you strength security stuff by using only secure protocol/port?

regards

**Comment by Zren** [comment]
`Ctrl+Shift+F` shows that `http://` only shows up for my `openweathermap.com` code for the weather stuff.

https://github.com/Zren/plasma-applet-eventcalendar/search?q=http

IIRC, OWM probably didn't have https back then. They do now, so thanks for pinging me about this issue.

Google Calendar should have always been https.

* https://github.com/Zren/plasma-applet-eventcalendar/blame/9ddc43e938059475b26d2cb865b449cd11078958/package/contents/ui/calendars/GoogleCalendarManager.qml#L95
* https://github.com/Zren/plasma-applet-eventcalendar/commit/b3ccd2b7f6e6131e33cf1727b5a6651d6256b2c7
* https://github.com/Zren/plasma-applet-eventcalendar/blame/0de715d04300c3dea6266507b6f2a473e4e4b9d9/org.kde.plasma.eventcalendar/package/contents/ui/PopupView.qml#L588
* https://github.com/Zren/plasma-applet-eventcalendar/commit/5009468a6637160894cac760304c551576ec9f68#diff-158857febeea53c5e61402ad5558f981R196

Granted I have never verified that QML sends https requests. "Trust, but verify".

**Comment by Zren** [comment]
For testing, it appears `netstat` and `sockstat` are deprecated (and not preinstalled in Manjaro) so I used the newer `ss` command.

```
watch -d ss -atnp
```

**Comment by Cherkah** [comment]
for each maj to the applet your cmd give: 

ESTAB        0        0           192.168.1.47:34374        82.196.7.246:80      users:(("http.so",pid=29266,fd=7))

**Comment by Zren** [comment]
If you delete the weather "city id" in the config, and confirm there's no `http.so` connections (might need to relog). Then do a manual refresh of the events/weather in the widget. You should no longer have any port 80 connections after the manual refresh in eventcalendar right?

A better command that only shows `http.so` connections by filtering using `grep`.

```bash
watch -d "ss -atnp | grep http.so"
```

**Comment by Cherkah** [comment]
you're right... now lets find the way to give back weather news to this applet; without this http.so!

there are a while that i'm stand on this trouble. 2-3 month ago http.so gave https and http. now only the unsecure one remains.

**Comment by Zren** [comment]
Should be fixed in v64
