### ISSUE TITLE
Link for google calendar not working (Brave Web Browser)

### ISSUE THREAD

**Issue by capoei** [Zren/plasma-applet-eventcalendar#87]
the link that tries to open is this:
https://accounts.google.com/o/oauth2/v2/auth?scope=https://www.googleapis.com/auth/calendar

and reults in:

"400. That’s an error.

Error: invalid_request

Required parameter is missing: response_type

Learn more

Request Details
scope=https://www.googleapis.com/auth/calendar
That’s all we know."

**Comment by Zren** [comment]
The URL contains `&response_type=code`, so I'm assuming the error was incorrect. It's probably from the Google Calendar API was having issues.

https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/config/GoogleCalendarSession.qml#L57

Does it still not work?

**Comment by capoei** [comment]
It still tries to open the same link.
can you tell me the whole link it is suposed to open? I don't know how to interpretate the code you sent

**Comment by capoei** [comment]
https://accounts.google.com/o/oauth2/v2/auth?scope=https://www.googleapis.com/auth/calendar&response_type=code

doesn't work either

**Comment by Zren** [comment]
It's suppose to be:

https://accounts.google.com/o/oauth2/v2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ftasks&response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&client_id=391436299960-o4hchof1u5vq49rdn2nlnlbs295qeqhj.apps.googleusercontent.com

It appears that it was not encoding the parameters for you for whatever reason. It treated the space in the scope as the end of the url.

`:` => `%3A`, `/` => `%2F`, `space` => `%20`, etc.

What version of Qt?

**Comment by capoei** [comment]
qt 5.13.0-7
browser=Brave

actualy the link opens with all the "%2F" thingies. So it surely is a problem with my setup here

**Comment by capoei** [comment]
with your link I could sign in. thanks
