### ISSUE TITLE
Rectangle border of weather is visible

### ISSUE THREAD

**Issue by Syderitic** [Zren/plasma-applet-eventcalendar#88]
https://github.com/Zren/plasma-applet-eventcalendar/blob/4190fec319f6a4bbc6d72a54689f537b757b5ab7/package/contents/ui/PopupView.qml#L301

Please change the border color to "transparent".
My buttonBackgroundColor is white and it took me a while to figure out why I had an annoying white rectangle in the middle of my weather forecast.
Unless there is a point to this being set as is, I recommend changing it to transparent.

Thank you for this awesome widget!

**Comment by Zren** [comment]
That should only appear if the weather is not configured or there's an error. If you're not using the meteogram, just disable it.

**Comment by Zren** [comment]
There was a bug in ba8f02c2 which caused an error. I think it caused the property declaration to error and revert to the default `visible: true` instead of only showing the outline when there's an error message.

**Comment by Syderitic** [comment]
Thank you. Just confirmed that ba8f02c fixed it!
I think you can close this now ;)
