### ISSUE TITLE
PIM All Day Events showing up a day early?

### ISSUE THREAD

**Issue by Zren** [Zren/plasma-applet-eventcalendar#9]
Ennai from https://www.opendesktop.org/p/998901 noticed this.

![image](https://user-images.githubusercontent.com/416367/37747967-1e21ddaa-2d58-11e8-97e7-541ceab14402.png)

**Comment by alekksander** [comment]
confirm

**Comment by Zren** [comment]
I'm 99% sure this is the same issue as #15, where the user lives in a timezone before GMT.
