### ISSUE TITLE
Stop Timer sound

### ISSUE THREAD

**Issue by DanielRios549** [Zren/plasma-applet-eventcalendar#93]
I think an option to stop the audio timer is missing, the default one is a simple beep, so it ends fast, but if I set a file with some seconds of duration, the only way to "stop" it is to mute the plasmashell playback stream. Consider adding this option, maybe in the right of the repeat or sound button, I think it will be very useful.

**Comment by AndydeCleyre** [comment]
Possibly relevant [comment](https://github.com/Zren/plasma-applets/issues/40#issuecomment-546514166)

**Comment by Zren** [comment]
The new timer notification.py script will stop the sfx if you click the notification.
