### ISSUE TITLE
It doesn't work with Qt 5.14 (beta1 so now)

### ISSUE THREAD

**Issue by pavbaranov** [Zren/plasma-applet-eventcalendar#99]
I know, that it's only Qt 5.14b1 so now, but maybe this info will be useful for you. Log:

> QML file loading error: file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/main.qml:100:37: Type PopupView unavailable
> file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/PopupView.qml:337:4: Type AgendaView unavailable
> file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaView.qml:71:15: Type AgendaListItem unavailable
> file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaListItem.qml:194:15: Type AgendaEventItem unavailable
> file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaEventItem.qml:253:4: Type EditEventForm unavailable
> file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/EditEventForm.qml:85:5: Type DurationSelector unavailable
> file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DurationSelector.qml:24:2: Type DateTimeSelector unavailable
> file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateTimeSelector.qml:27:2: Type DateSelector unavailable
> file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateSelector.qml:63:33: Cannot assign object of type "T.Popup" to property of type "Popup_QMLTYPE_287*" as the former is neither the same as the latter nor a sub-class of it.
And of course it doesn't work. 
Additional information:
system: Arch Linux (testing with kde-unstable enabled)
Qt version: 5.14 beta1
KF5 version: 5.62 (but it doesn't work on 5.63rc, too)
Plasma version: 5.16.90 (but with Qt 5.13 works well)

**Comment by Zren** [comment]
If you can, change the popup declaration line from `DateSelector.qml`

`property Controls.Popup popup: T.Popup {`

to

`property T.Popup popup: T.Popup {`

or

`property var popup: T.Popup {`

if that doesn't work.

To test if changes worked, run `plasmawindowed org.kde.plasma.eventcalendar`. If it does work, restart plasmashell by relogging.

**Comment by pavbaranov** [comment]
I try both, but it doesn't work. Output error is the same.

**Comment by Zren** [comment]
This line should definitely being changing:

> Cannot assign object of type "T.Popup" to property of type "Popup_QMLTYPE_287*" as the former is neither the same as the latter nor a sub-class of it.

You're editing:

`/usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateSelector.qml` right? It's installed as sudo? You're sure you don't have it installed to `~/.local/share/plasma/plasmoids` right?

What if you change it to:

`property Controls.Popup popup: Controls.Popup {`

or 

`property var popup: Controls.Popup {`

Worst comes to worse, you can delete the entire `popup` section, then delete `onPressed: popup.open()`.

The DateSelector is disabled in v64 anyways.

**Comment by pavbaranov** [comment]
Yes, I was edited this file and of course as "sudo" (root, etc.). Both your proposal not works. I have v64 version from AUR, so I have it in /usr/share/plasma/plasmoids/ 
This line:

> property Controls.Popup popup

> 
Is only in /usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/TimeSelector.qml but only as:

> 	property Controls.Popup popup: T.Popup 

Should I change it as you propose?

**Comment by Zren** [comment]
Should be fixed in the just released v66.
